### ISSUE TITLE
Save explored areas state

### ISSUE THREAD

**Issue by abdd1998** [mkwozniak/mangofogunity2d#1]
Is there a way to save the state of explored areas in the fog so when loading a game we could load the explored areas?

**Comment by mkwozniak** [comment]
Yes, if you take a look at the example scenes there is an implementation of saving/loading the buffers. 
In MangoFogInstance there is two methods:

SaveChunkBufferToSlot
LoadSlotBufferToChunk

**Comment by abdd1998** [comment]
Got it thank you so much!
